kubectl apply -f adservice-service.yaml -n microservices
kubectl apply -f cartservice-service.yaml -n microservices
kubectl apply -f checkoutservice-service.yaml -n microservices
kubectl apply -f currencyservice-service.yaml -n microservices
kubectl apply -f emailservice-service.yaml -n microservices
kubectl apply -f frontend-service.yaml -n microservices
kubectl apply -f paymentservice-service.yaml -n microservices
kubectl apply -f productcatalogservice-service.yaml -n microservices
kubectl apply -f recommendationservice-service.yaml -n microservices
kubectl apply -f redis-cart-service.yaml -n microservices
kubectl apply -f shippingservice-service.yaml -n microservices