apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  labels:
    app: emailservice
spec:
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
        - name: service
          image: gcr.io/google-samples/microservices-demo/emailservice:v0.9.0
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: DISABLE_PROFILER
              value: "1"
            - name: DISABLE_TRACKING
              value: "1"
          livenessProbe:
            periodSeconds: 5
            grpc:
              port: 8080
          readinessProbe:
            periodSeconds: 5
            grpc:
              port: 8080