apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
        - name: service
          image: gcr.io/google-samples/microservices-demo/paymentservice
          ports:
            - containerPort: 50051
          env:
            - name: PORT
              value: "50051"